# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_STATE(object):
    def setupUi(self, STATE):
        STATE.setObjectName("STATE")
        STATE.resize(1171, 571)
        self.op = QtWidgets.QTabWidget(STATE)
        self.op.setGeometry(QtCore.QRect(0, 0, 1161, 561))
        self.op.setObjectName("op")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 90, 581, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(0, 0, 1151, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Jwtable = QtWidgets.QTableView(self.tab_2)
        self.Jwtable.setGeometry(QtCore.QRect(20, 100, 1131, 431))
        self.Jwtable.setObjectName("Jwtable")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1141, 77))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Jwunit = QtWidgets.QLineEdit(self.layoutWidget)
        self.Jwunit.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwunit.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwunit.setObjectName("Jwunit")
        self.gridLayout.addWidget(self.Jwunit, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.Jwtype = QtWidgets.QLineEdit(self.layoutWidget)
        self.Jwtype.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwtype.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwtype.setObjectName("Jwtype")
        self.gridLayout.addWidget(self.Jwtype, 0, 3, 1, 1)
        self.Jwquery = QtWidgets.QPushButton(self.layoutWidget)
        self.Jwquery.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwquery.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwquery.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Jwquery.setObjectName("Jwquery")
        self.gridLayout.addWidget(self.Jwquery, 1, 5, 1, 1)
        self.Jwsample = QtWidgets.QLineEdit(self.layoutWidget)
        self.Jwsample.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwsample.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwsample.setObjectName("Jwsample")
        self.gridLayout.addWidget(self.Jwsample, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.Jwname = QtWidgets.QLineEdit(self.layoutWidget)
        self.Jwname.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwname.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwname.setObjectName("Jwname")
        self.gridLayout.addWidget(self.Jwname, 0, 1, 1, 1)
        self.Jwsub = QtWidgets.QPushButton(self.layoutWidget)
        self.Jwsub.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwsub.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwsub.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Jwsub.setObjectName("Jwsub")
        self.gridLayout.addWidget(self.Jwsub, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.Jwid = QtWidgets.QLineEdit(self.layoutWidget)
        self.Jwid.setMinimumSize(QtCore.QSize(70, 20))
        self.Jwid.setMaximumSize(QtCore.QSize(70, 20))
        self.Jwid.setObjectName("Jwid")
        self.gridLayout.addWidget(self.Jwid, 0, 0, 1, 1)
        self.tip = QtWidgets.QLabel(self.tab_2)
        self.tip.setGeometry(QtCore.QRect(30, 10, 54, 12))
        self.tip.setText("")
        self.tip.setObjectName("tip")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(0, 80, 1151, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.op.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(110, 10, 20, 521))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Rwtable = QtWidgets.QTableView(self.tab)
        self.Rwtable.setGeometry(QtCore.QRect(120, 40, 1031, 491))
        self.Rwtable.setObjectName("Rwtable")
        self.Rwquery = QtWidgets.QPushButton(self.tab)
        self.Rwquery.setGeometry(QtCore.QRect(130, 10, 75, 23))
        self.Rwquery.setObjectName("Rwquery")
        self.Rwchange = QtWidgets.QPushButton(self.tab)
        self.Rwchange.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.Rwchange.setObjectName("Rwchange")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 91, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Rwgetid = QtWidgets.QPushButton(self.layoutWidget1)
        self.Rwgetid.setObjectName("Rwgetid")
        self.verticalLayout.addWidget(self.Rwgetid)
        self.Rwidtable = QtWidgets.QTableView(self.layoutWidget1)
        self.Rwidtable.setObjectName("Rwidtable")
        self.verticalLayout.addWidget(self.Rwidtable)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 140, 91, 392))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.re = QtWidgets.QLabel(self.layoutWidget2)
        self.re.setObjectName("re")
        self.verticalLayout_2.addWidget(self.re)
        self.Rwid = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwid.setObjectName("Rwid")
        self.verticalLayout_2.addWidget(self.Rwid)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.Rwnum = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwnum.setObjectName("Rwnum")
        self.verticalLayout_2.addWidget(self.Rwnum)
        self.Rwupricedf = QtWidgets.QLabel(self.layoutWidget2)
        self.Rwupricedf.setObjectName("Rwupricedf")
        self.verticalLayout_2.addWidget(self.Rwupricedf)
        self.Rwuprice = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwuprice.setObjectName("Rwuprice")
        self.verticalLayout_2.addWidget(self.Rwuprice)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.Rwprice = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwprice.setObjectName("Rwprice")
        self.verticalLayout_2.addWidget(self.Rwprice)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.Rwtime = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwtime.setEnabled(False)
        self.Rwtime.setText("")
        self.Rwtime.setReadOnly(False)
        self.Rwtime.setObjectName("Rwtime")
        self.verticalLayout_2.addWidget(self.Rwtime)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.Rwviaperson = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwviaperson.setObjectName("Rwviaperson")
        self.verticalLayout_2.addWidget(self.Rwviaperson)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.Rwsaveperson = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwsaveperson.setObjectName("Rwsaveperson")
        self.verticalLayout_2.addWidget(self.Rwsaveperson)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.instore = QtWidgets.QComboBox(self.layoutWidget2)
        self.instore.setObjectName("instore")
        self.instore.addItem("")
        self.instore.addItem("")
        self.instore.addItem("")
        self.instore.addItem("")
        self.instore.addItem("")
        self.verticalLayout_2.addWidget(self.instore)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.Rwtxt = QtWidgets.QLineEdit(self.layoutWidget2)
        self.Rwtxt.setObjectName("Rwtxt")
        self.verticalLayout_2.addWidget(self.Rwtxt)
        self.getTimeBtn = QtWidgets.QPushButton(self.tab)
        self.getTimeBtn.setGeometry(QtCore.QRect(290, 10, 81, 23))
        self.getTimeBtn.setObjectName("getTimeBtn")
        self.intip = QtWidgets.QLabel(self.tab)
        self.intip.setGeometry(QtCore.QRect(440, 20, 54, 12))
        self.intip.setText("")
        self.intip.setObjectName("intip")
        self.op.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Cwquery = QtWidgets.QPushButton(self.tab_6)
        self.Cwquery.setGeometry(QtCore.QRect(120, 20, 75, 23))
        self.Cwquery.setObjectName("Cwquery")
        self.Cwchange = QtWidgets.QPushButton(self.tab_6)
        self.Cwchange.setGeometry(QtCore.QRect(200, 20, 75, 23))
        self.Cwchange.setObjectName("Cwchange")
        self.line_10 = QtWidgets.QFrame(self.tab_6)
        self.line_10.setGeometry(QtCore.QRect(100, 10, 16, 511))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Cwtable = QtWidgets.QTableView(self.tab_6)
        self.Cwtable.setGeometry(QtCore.QRect(110, 50, 1041, 481))
        self.Cwtable.setObjectName("Cwtable")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 91, 111))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Cwgetid = QtWidgets.QPushButton(self.layoutWidget3)
        self.Cwgetid.setObjectName("Cwgetid")
        self.verticalLayout_5.addWidget(self.Cwgetid)
        self.Cwidtable = QtWidgets.QTableView(self.layoutWidget3)
        self.Cwidtable.setObjectName("Cwidtable")
        self.verticalLayout_5.addWidget(self.Cwidtable)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 140, 91, 392))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.Cwid = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwid.setObjectName("Cwid")
        self.verticalLayout_6.addWidget(self.Cwid)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.Cwnum = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwnum.setObjectName("Cwnum")
        self.verticalLayout_6.addWidget(self.Cwnum)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.Cwuprice = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwuprice.setObjectName("Cwuprice")
        self.verticalLayout_6.addWidget(self.Cwuprice)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.Cwprice = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwprice.setObjectName("Cwprice")
        self.verticalLayout_6.addWidget(self.Cwprice)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_6.addWidget(self.label_33)
        self.Cwtime = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwtime.setEnabled(False)
        self.Cwtime.setObjectName("Cwtime")
        self.verticalLayout_6.addWidget(self.Cwtime)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        self.Cwgetperson = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwgetperson.setObjectName("Cwgetperson")
        self.verticalLayout_6.addWidget(self.Cwgetperson)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.Cwviaperson = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwviaperson.setObjectName("Cwviaperson")
        self.verticalLayout_6.addWidget(self.Cwviaperson)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.outstore = QtWidgets.QComboBox(self.layoutWidget4)
        self.outstore.setObjectName("outstore")
        self.outstore.addItem("")
        self.outstore.addItem("")
        self.outstore.addItem("")
        self.outstore.addItem("")
        self.outstore.addItem("")
        self.verticalLayout_6.addWidget(self.outstore)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_6.addWidget(self.label_37)
        self.Cwtxt = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Cwtxt.setObjectName("Cwtxt")
        self.verticalLayout_6.addWidget(self.Cwtxt)
        self.getCwtime = QtWidgets.QPushButton(self.tab_6)
        self.getCwtime.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.getCwtime.setObjectName("getCwtime")
        self.Cwtable.raise_()
        self.Cwquery.raise_()
        self.Cwchange.raise_()
        self.line_10.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.getCwtime.raise_()
        self.op.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.reservetable = QtWidgets.QTableView(self.tab_7)
        self.reservetable.setGeometry(QtCore.QRect(10, 30, 1141, 501))
        self.reservetable.setObjectName("reservetable")
        self.Kc = QtWidgets.QPushButton(self.tab_7)
        self.Kc.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.Kc.setObjectName("Kc")
        self.op.addTab(self.tab_7, "")

        self.retranslateUi(STATE)
        self.op.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(STATE)

    def retranslateUi(self, STATE):
        _translate = QtCore.QCoreApplication.translate
        STATE.setWindowTitle(_translate("STATE", "Form"))
        self.label_4.setText(_translate("STATE", "种类"))
        self.label_5.setText(_translate("STATE", "计量单位"))
        self.Jwquery.setText(_translate("STATE", "查询/修改"))
        self.label_3.setText(_translate("STATE", "规格型号"))
        self.label_2.setText(_translate("STATE", "物资名称"))
        self.Jwsub.setText(_translate("STATE", "提交"))
        self.label.setText(_translate("STATE", "物资编号"))
        self.op.setTabText(self.op.indexOf(self.tab_2), _translate("STATE", "物资信息录入查询"))
        self.Rwquery.setText(_translate("STATE", "提交"))
        self.Rwchange.setText(_translate("STATE", "查询/修改"))
        self.Rwgetid.setText(_translate("STATE", "获取物资编号"))
        self.re.setText(_translate("STATE", "商品编号"))
        self.label_6.setText(_translate("STATE", "数量"))
        self.Rwupricedf.setText(_translate("STATE", "单价"))
        self.label_8.setText(_translate("STATE", "金额"))
        self.label_9.setText(_translate("STATE", "入库时间"))
        self.label_10.setText(_translate("STATE", "经办人"))
        self.label_11.setText(_translate("STATE", "保管人"))
        self.label_12.setText(_translate("STATE", "仓库"))
        self.instore.setItemText(0, _translate("STATE", "1"))
        self.instore.setItemText(1, _translate("STATE", "2"))
        self.instore.setItemText(2, _translate("STATE", "3"))
        self.instore.setItemText(3, _translate("STATE", "4"))
        self.instore.setItemText(4, _translate("STATE", "5"))
        self.label_13.setText(_translate("STATE", "备注"))
        self.getTimeBtn.setText(_translate("STATE", "获取当前时间"))
        self.op.setTabText(self.op.indexOf(self.tab), _translate("STATE", "入库信息录入查询"))
        self.Cwquery.setText(_translate("STATE", "提交"))
        self.Cwchange.setText(_translate("STATE", "查询/修改"))
        self.Cwgetid.setText(_translate("STATE", "获取物资编号"))
        self.label_29.setText(_translate("STATE", "物资编号"))
        self.label_30.setText(_translate("STATE", "数量"))
        self.label_31.setText(_translate("STATE", "单价"))
        self.label_32.setText(_translate("STATE", "金额"))
        self.label_33.setText(_translate("STATE", "领用时间"))
        self.label_34.setText(_translate("STATE", "领用人"))
        self.label_35.setText(_translate("STATE", "经办人"))
        self.label_36.setText(_translate("STATE", "仓库"))
        self.outstore.setItemText(0, _translate("STATE", "1"))
        self.outstore.setItemText(1, _translate("STATE", "2"))
        self.outstore.setItemText(2, _translate("STATE", "3"))
        self.outstore.setItemText(3, _translate("STATE", "4"))
        self.outstore.setItemText(4, _translate("STATE", "5"))
        self.label_37.setText(_translate("STATE", "备注"))
        self.getCwtime.setText(_translate("STATE", "获取时间"))
        self.op.setTabText(self.op.indexOf(self.tab_6), _translate("STATE", "出库信息录入查询"))
        self.Kc.setText(_translate("STATE", "查询"))
        self.op.setTabText(self.op.indexOf(self.tab_7), _translate("STATE", "库存信息查询"))

